"ASU112s Fall 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4050?committee_id=31489"
"PHM111s Fall 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4070?committee_id=31165"
"PHM121s Fall 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4087?committee_id=31513"
"EPM112s Fall 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4455?committee_id=31087"
"EPM111s Fall 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4454?committee_id=31086"
"CSE111s Fall 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4582?committee_id=31031"
"ENG011s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4027?committee_id=27982"
"PHM013s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4036?committee_id=27987"
"ASU101s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/9775?committee_id=29541"
"MDP081s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4030?committee_id=27984"
"PHM022s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4038?committee_id=27989"
"PHM032s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4040?committee_id=27991"
"CEP011s Spring 2023" = "https://eng.asu.edu.eg/public/dashboard/courses/show/4023?committee_id=27980"
